export const columns = {
  users: [
    {
      key: "id",
      name: "ID",
      sortable: true,
      editable: false,
      searchable: true,
      showable: true,
      width: "",
    },
    {
      key: "email",
      name: "email",
      sortable: false,
      editable: false,
      searchable: true,
      showable: true,
      width: "120px",
    },
    {
      key: "role",
      name: "role",
      sortable: false,
      editable: false,
      searchable: true,
      showable: true,
      width: "",
    },
    {
      key: "first_name",
      name: "Name",
      sortable: true,
      editable: true,
      searchable: false,
      showable: true,
      width: "",
    },
    {
      key: "last_name",
      name: "Surname",
      sortable: true,
      editable: true,
      searchable: false,
      showable: true,
      width: "",
    },
    {
      key: "phone",
      name: "Phone",
      sortable: false,
      editable: true,
      searchable: false,
      showable: true,
      width: "100px",
    },
    {
      key: "birthday",
      name: "Birthday",
      sortable: false,
      editable: true,
      searchable: false,
      showable: true,
      width: "",
    },
    {
      key: "street",
      name: "Street",
      sortable: false,
      editable: true,
      searchable: false,
      showable: true,
      width: "100px",
    },
    {
      key: "zip",
      name: "Zip",
      sortable: false,
      editable: true,
      searchable: false,
      showable: true,
      width: "",
    },
    {
      key: "city",
      name: "City",
      sortable: false,
      editable: true,
      searchable: false,
      showable: true,
      width: "70px",
    },
    {
      key: "country",
      name: "Country",
      sortable: false,
      editable: true,
      searchable: false,
      showable: true,
      width: "70px",
    },
    {
      key: "last_login",
      name: "Last Login",
      sortable: false,
      editable: false,
      searchable: false,
      showable: true,
      width: "30px",
    },
    {
      key: "failed_logins",
      name: "Failed Logins",
      sortable: false,
      editable: true,
      searchable: false,
      showable: true,
      width: "30px",
    },
    {
      key: "has_verified_email",
      name: "Email Verified",
      sortable: false,
      editable: true,
      searchable: false,
      showable: true,
      width: "30px",
    },
  ],
  passes: [
    {
      key: "id",
      name: "ID",
      sortable: true,
      editable: false,
      searchable: true,
    },
    {
      key: "seat_id",
      name: "Seat ID",
      sortable: true,
      editable: false,
      searchable: true,
    },
    {
      key: "season_id",
      name: "Season ID",
      sortable: true,
      editable: false,
      searchable: true,
    },
    {
      key: "user_id",
      name: "User ID",
      sortable: true,
      editable: true,
      searchable: true,
    },
    {
      key: "assign_token",
      name: "Token",
      sortable: false,
      editable: false,
      searchable: false,
    },
    {
      key: "type",
      name: "Type",
      sortable: false,
      editable: false,
      searchable: false,
    },
    {
      key: "first_name",
      name: "Name",
      sortable: true,
      editable: true,
      searchable: true,
    },
    {
      key: "last_name",
      name: "Surname",
      sortable: true,
      editable: true,
      searchable: false,
    },
    {
      key: "street",
      name: "Street",
      sortable: true,
      editable: true,
      searchable: false,
    },
    {
      key: "zip",
      name: "Zip",
      sortable: true,
      editable: true,
      searchable: false,
    },
    {
      key: "city",
      name: "City",
      sortable: true,
      editable: true,
      searchable: false,
    },
    {
      key: "country",
      name: "Country",
      sortable: true,
      editable: true,
      searchable: false,
    },
  ],
  accesses: [
    {
      key: "id",
      name: "ID",
      sortable: true,
      editable: false,
      searchable: true,
    },
    {
      key: "game_id",
      name: "Game ID",
      sortable: true,
      editable: false,
      searchable: true,
    },
    {
      key: "Pass_id",
      name: "Pass ID",
      sortable: true,
      editable: false,
      searchable: true,
    },
    {
      key: "seat_id",
      name: "Seat ID",
      sortable: true,
      editable: false,
      searchable: true,
    },
    {
      key: "access_token",
      name: "Token",
      sortable: false,
      editable: false,
      searchable: false,
    },
    {
      key: "first_name",
      name: "Name",
      sortable: true,
      editable: true,
      searchable: true,
    },
    {
      key: "last_name",
      name: "Surname",
      sortable: true,
      editable: true,
      searchable: true,
    },
    {
      key: "phone",
      name: "Phone",
      sortable: false,
      editable: true,
      searchable: true,
    },
    {
      key: "birthday",
      name: "Birthday",
      sortable: false,
      editable: true,
      searchable: true,
    },
    {
      key: "street",
      name: "Street",
      sortable: true,
      editable: true,
      searchable: true,
    },
    {
      key: "zip",
      name: "Zip",
      sortable: true,
      editable: true,
      searchable: true,
    },
    {
      key: "city",
      name: "City",
      sortable: true,
      editable: true,
      searchable: true,
    },
    {
      key: "country",
      name: "Country",
      sortable: true,
      editable: true,
      searchable: true,
    },
    {
      key: "email",
      name: "Email",
      sortable: true,
      editable: false,
      searchable: true,
    },
    {
      key: "accept_marketing",
      name: "Marketing",
      sortable: false,
      editable: false,
      searchable: false,
    },
    {
      key: "scanned_at",
      name: "Scanned At",
      sortable: false,
      editable: false,
      searchable: false,
    },
  ],
  scenarios: [
    {
      key: "id",
      name: "ID",
      sortable: true,
      editable: false,
      searchable: true,
      showable: true,
    },
    {
      key: "title",
      name: "Title",
      sortable: true,
      editable: true,
      searchable: true,
      showable: true,
    },
  ],
  seats: [
    // {
    //   key: "id",
    //   name: "ID",
    //   sortable: true,
    //   editable: false,
    //   searchable: false,
    //   showable: false,
    // },
    {
      key: "row",
      name: "Row",
      sortable: false,
      editable: false,
      searchable: true,
      showable: false,
    },
    {
      key: "num",
      name: "Num",
      sortable: true,
      editable: false,
      searchable: false,
      showable: false,
    }
  ],
  seatGroups: [
    // {
    //   key: "id",
    //   name: "ID",
    //   sortable: true,
    //   editable: false,
    //   searchable: false,
    //   showable: false,
    // },
    {
      key: "title",
      name: "title",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    }
  ],
  seatMaps: [
    {
      key: "id",
      name: "ID",
      sortable: true,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "scenario_id",
      name: "Scenario ID",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "original_seat_id",
      name: "Original Seat ID",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "mapped_seat_id",
      name: "Mapped Seat ID",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
  ],
  games: [
    {
      key: "id",
      name: "ID",
      sortable: true,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "scenario_id",
      name: "Scenario ID",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "away_team_id",
      name: "Away Team",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "home_team_id",
      name: "Home Team",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "season_id",
      name: "Season ID",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "location",
      name: "Location",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "date",
      name: "Date",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
  ],
  seasons: [
    {
      key: "createdAt",
      name: "createdAt",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "updatedAt",
      name: "updatedAt",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "deletedAt",
      name: "deletedAt",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "id",
      name: "ID",
      sortable: true,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "title",
      name: "title",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
  ],
  scanners: [
    {
      key: "createdAt",
      name: "createdAt",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "updatedAt",
      name: "updatedAt",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "deletedAt",
      name: "deletedAt",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "id",
      name: "ID",
      sortable: true,
      editable: false,
      searchable: false,
      showable: false,
    },
    {
      key: "title",
      name: "title",
      sortable: false,
      editable: false,
      searchable: false,
      showable: false,
    },
  ],
};
